// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.1
// source: assignment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignmentInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Formulas []*Formula      `protobuf:"bytes,1,rep,name=formulas,proto3" json:"formulas,omitempty"`
	Mapping  map[string]bool `protobuf:"bytes,2,rep,name=mapping,proto3" json:"mapping,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *AssignmentInput) Reset() {
	*x = AssignmentInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_assignment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignmentInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentInput) ProtoMessage() {}

func (x *AssignmentInput) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentInput.ProtoReflect.Descriptor instead.
func (*AssignmentInput) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{0}
}

func (x *AssignmentInput) GetFormulas() []*Formula {
	if x != nil {
		return x.Formulas
	}
	return nil
}

func (x *AssignmentInput) GetMapping() map[string]bool {
	if x != nil {
		return x.Mapping
	}
	return nil
}

var File_assignment_proto protoreflect.FileDescriptor

var file_assignment_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x0d,
	0x66, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbf, 0x01,
	0x0a, 0x0f, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x12, 0x2c, 0x0a, 0x08, 0x66, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x2e, 0x46, 0x6f,
	0x72, 0x6d, 0x75, 0x6c, 0x61, 0x52, 0x08, 0x66, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x73, 0x12,
	0x42, 0x0a, 0x07, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x2e, 0x4d, 0x61,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x6d, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x1a, 0x3a, 0x0a, 0x0c, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42,
	0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6f,
	0x6f, 0x6c, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x6e, 0x67,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x69, 0x6f, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_assignment_proto_rawDescOnce sync.Once
	file_assignment_proto_rawDescData = file_assignment_proto_rawDesc
)

func file_assignment_proto_rawDescGZIP() []byte {
	file_assignment_proto_rawDescOnce.Do(func() {
		file_assignment_proto_rawDescData = protoimpl.X.CompressGZIP(file_assignment_proto_rawDescData)
	})
	return file_assignment_proto_rawDescData
}

var file_assignment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_assignment_proto_goTypes = []interface{}{
	(*AssignmentInput)(nil), // 0: assignment.AssignmentInput
	nil,                     // 1: assignment.AssignmentInput.MappingEntry
	(*Formula)(nil),         // 2: formula.Formula
}
var file_assignment_proto_depIdxs = []int32{
	2, // 0: assignment.AssignmentInput.formulas:type_name -> formula.Formula
	1, // 1: assignment.AssignmentInput.mapping:type_name -> assignment.AssignmentInput.MappingEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_assignment_proto_init() }
func file_assignment_proto_init() {
	if File_assignment_proto != nil {
		return
	}
	file_formula_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_assignment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignmentInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_assignment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_assignment_proto_goTypes,
		DependencyIndexes: file_assignment_proto_depIdxs,
		MessageInfos:      file_assignment_proto_msgTypes,
	}.Build()
	File_assignment_proto = out.File
	file_assignment_proto_rawDesc = nil
	file_assignment_proto_goTypes = nil
	file_assignment_proto_depIdxs = nil
}
