// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.1
// source: maxsat_input.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MaxSatInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HardFormulas []string             `protobuf:"bytes,1,rep,name=hardFormulas,proto3" json:"hardFormulas,omitempty"`
	SoftFormulas []*FormulaWithWeight `protobuf:"bytes,2,rep,name=softFormulas,proto3" json:"softFormulas,omitempty"`
}

func (x *MaxSatInput) Reset() {
	*x = MaxSatInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maxsat_input_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxSatInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxSatInput) ProtoMessage() {}

func (x *MaxSatInput) ProtoReflect() protoreflect.Message {
	mi := &file_maxsat_input_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxSatInput.ProtoReflect.Descriptor instead.
func (*MaxSatInput) Descriptor() ([]byte, []int) {
	return file_maxsat_input_proto_rawDescGZIP(), []int{0}
}

func (x *MaxSatInput) GetHardFormulas() []string {
	if x != nil {
		return x.HardFormulas
	}
	return nil
}

func (x *MaxSatInput) GetSoftFormulas() []*FormulaWithWeight {
	if x != nil {
		return x.SoftFormulas
	}
	return nil
}

type FormulaWithWeight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Formula string `protobuf:"bytes,1,opt,name=formula,proto3" json:"formula,omitempty"`
	Weight  int64  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (x *FormulaWithWeight) Reset() {
	*x = FormulaWithWeight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maxsat_input_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormulaWithWeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormulaWithWeight) ProtoMessage() {}

func (x *FormulaWithWeight) ProtoReflect() protoreflect.Message {
	mi := &file_maxsat_input_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormulaWithWeight.ProtoReflect.Descriptor instead.
func (*FormulaWithWeight) Descriptor() ([]byte, []int) {
	return file_maxsat_input_proto_rawDescGZIP(), []int{1}
}

func (x *FormulaWithWeight) GetFormula() string {
	if x != nil {
		return x.Formula
	}
	return ""
}

func (x *FormulaWithWeight) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

var File_maxsat_input_proto protoreflect.FileDescriptor

var file_maxsat_input_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x61, 0x78, 0x73, 0x61, 0x74, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x61, 0x78, 0x73, 0x61, 0x74, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x22, 0x75, 0x0a, 0x0b, 0x4d, 0x61, 0x78, 0x53, 0x61, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x12, 0x22, 0x0a, 0x0c, 0x68, 0x61, 0x72, 0x64, 0x46, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x61, 0x72, 0x64, 0x46, 0x6f, 0x72, 0x6d,
	0x75, 0x6c, 0x61, 0x73, 0x12, 0x42, 0x0a, 0x0c, 0x73, 0x6f, 0x66, 0x74, 0x46, 0x6f, 0x72, 0x6d,
	0x75, 0x6c, 0x61, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x61, 0x78,
	0x73, 0x61, 0x74, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61,
	0x57, 0x69, 0x74, 0x68, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x0c, 0x73, 0x6f, 0x66, 0x74,
	0x46, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x73, 0x22, 0x45, 0x0a, 0x11, 0x46, 0x6f, 0x72, 0x6d,
	0x75, 0x6c, 0x61, 0x57, 0x69, 0x74, 0x68, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x66, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x66, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42,
	0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6f,
	0x6f, 0x6c, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x6e, 0x67,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x69, 0x6f, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_maxsat_input_proto_rawDescOnce sync.Once
	file_maxsat_input_proto_rawDescData = file_maxsat_input_proto_rawDesc
)

func file_maxsat_input_proto_rawDescGZIP() []byte {
	file_maxsat_input_proto_rawDescOnce.Do(func() {
		file_maxsat_input_proto_rawDescData = protoimpl.X.CompressGZIP(file_maxsat_input_proto_rawDescData)
	})
	return file_maxsat_input_proto_rawDescData
}

var file_maxsat_input_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_maxsat_input_proto_goTypes = []interface{}{
	(*MaxSatInput)(nil),       // 0: maxsatinput.MaxSatInput
	(*FormulaWithWeight)(nil), // 1: maxsatinput.FormulaWithWeight
}
var file_maxsat_input_proto_depIdxs = []int32{
	1, // 0: maxsatinput.MaxSatInput.softFormulas:type_name -> maxsatinput.FormulaWithWeight
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_maxsat_input_proto_init() }
func file_maxsat_input_proto_init() {
	if File_maxsat_input_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_maxsat_input_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxSatInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_maxsat_input_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormulaWithWeight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_maxsat_input_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_maxsat_input_proto_goTypes,
		DependencyIndexes: file_maxsat_input_proto_depIdxs,
		MessageInfos:      file_maxsat_input_proto_msgTypes,
	}.Build()
	File_maxsat_input_proto = out.File
	file_maxsat_input_proto_rawDesc = nil
	file_maxsat_input_proto_goTypes = nil
	file_maxsat_input_proto_depIdxs = nil
}
